name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  checks: write

jobs:
  setup-and-test:
    name: Install, Lint, Test, Security
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run lint
        run: |
          if npm run lint --silent; then
            echo "lint ok"
          else
            echo "lint failed"
            exit 1
          fi

      - name: Run tests
        run: |
          npm test --silent || (echo "No tests or tests failed"; exit 1 )

      - name: Run npm audit (security)
        run: |
          npm audit --audit-level=moderate || true

      - name: Upload logs artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ci-logs-${{ matrix.node-version }}
          path: |
            npm-debug.log
            test-results || true
