name: Release Drafter and Release

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
  pull_request:
    types: [closed]

jobs:
  create-release:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  draft-release-notes:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.pull_request.merged == true
    steps:
      - name: Update release-draft (simple)
        run: |
          echo "Merged PR #${{ github.event.pull_request.number }} by ${{ github.event.pull_request.user.login }}"
